% Produced by CVXGEN, 2018-12-05 06:56:50 -0500.
% CVXGEN is Copyright (C) 2006-2017 Jacob Mattingley, jem@cvxgen.com.
% The code in this file is Copyright (C) 2006-2017 Jacob Mattingley.
% CVXGEN, or solvers produced by CVXGEN, cannot be used for commercial
% applications without prior written permission from Jacob Mattingley.

% Filename: cvxsolve.m.
% Description: Solution file, via cvx, for use with sample.m.
function [vars, status] = cvxsolve(params, settings)
L = params.L;
N = params.N;
Q = params.Q;
W = params.W;
alpha = params.alpha;
dbt = params.dbt;
dbx = params.dbx;
f = params.f;
g = params.g;
norm_dbx = params.norm_dbx;
cvx_begin
  % Caution: automatically generated by cvxgen. May be incorrect.
  variable u(3, 1);

  minimize(quad_form(u, Q));
  subject to
    dbx'*(f + g*u) >= norm_dbx*(W + L) - N*(dbt + alpha);
cvx_end
vars.u = u;
status.cvx_status = cvx_status;
% Provide a drop-in replacement for csolve.
status.optval = cvx_optval;
status.converged = strcmp(cvx_status, 'Solved');
